export * from "./header/header.component";
export * from "./button/button.component";
export * from "./info/info.component";
export * from "./search/search.component";
export * from "./course-card/course-card.component";
export * from "./course-form/course-form.component";
export * from "./page-not-found/page-not-found.component";
export * from "./login-form/login-form.component";
export * from "./registration-form/registration-form.component";
